version: "3.8"

services:
  backend:
    image: cloud-campus-backend
    container_name: cloud-campus-api
    build: .
    ports:
      - "3001:5000"
    env_file:
      - .env
    restart: unless-stopped
